// Initial, reviewed import. Existing Markdown files are never overwritten.
import fs from 'node:fs';
import path from 'node:path';

const original = [
  [
    'refero',
    'Refero Styles',
    '从字体、配色和布局出发，观察不同网站的设计语言。',
    'https://styles.refero.design/',
    '灵感',
    '设计系统,排版',
    'Re',
    'blue',
  ],
  [
    'motionsites',
    'MotionSites',
    '收集带有动效的网页，参考页面节奏和 AI 设计提示。',
    'https://motionsites.ai/',
    '灵感',
    '动效,AI',
    'M',
    'violet',
  ],
  [
    'react-bits',
    'React Bits',
    '浏览可用于 React 的动画、背景和交互组件。',
    'https://reactbits.dev/',
    '组件',
    'React,动效',
    'Rb',
    'teal',
  ],
  [
    '21st-dev',
    '21st.dev',
    '按界面任务浏览 React 组件、页面区块与模板。',
    'https://21st.dev/',
    '组件',
    'React,页面区块',
    '21',
    'blue',
  ],
  [
    'three-ui',
    'ThreeUI',
    '探索 3D 风格的界面与网页组件，收集空间表现的参考。',
    'https://threeui.com/browse',
    '组件',
    '3D,交互',
    '3D',
    'violet',
  ],
  [
    'navbar-gallery',
    'Navbar Gallery',
    '只看导航怎么做：菜单层级、品牌位置与响应式布局。',
    'https://www.navbar.gallery/',
    '灵感',
    '导航,页面区块',
    'N',
    'slate',
  ],
  [
    'supahero',
    'SupaHero',
    '从首屏构图、标题和视觉重点中寻找页面开场的思路。',
    'https://supahero.io/',
    '灵感',
    'Hero,页面区块',
    'S',
    'orange',
  ],
  [
    '404-design',
    '404s.design',
    '观察错误页面如何说明问题，并帮助访问者找到下一步。',
    'https://www.404s.design/',
    '灵感',
    '空状态,页面区块',
    '404',
    'rose',
  ],
  [
    'footer-design',
    'Footer.design',
    '收集页脚的信息分组、链接组织和页面收尾方式。',
    'https://www.footer.design/',
    '灵感',
    '页脚,页面区块',
    'F',
    'slate',
  ],
  [
    'cta-gallery',
    'CTA Gallery',
    '参考行动按钮的措辞、位置和上下文，理解页面主次。',
    'https://www.cta.gallery/',
    '灵感',
    '按钮,页面区块',
    '↗',
    'blue',
  ],
  [
    'unsection',
    'Unsection',
    '把整页拆成区块，按正在设计的局部寻找灵感。',
    'https://www.unsection.com/',
    '灵感',
    '页面区块,布局',
    'U',
    'teal',
  ],
  [
    '60fps',
    '60fps.design',
    '观察真实界面的动效细节、状态切换和交互节奏。',
    'https://60fps.design/',
    '灵感',
    '动效,交互',
    '60',
    'orange',
  ],
  [
    'design-spells',
    'Design Spells',
    '关注让界面更有趣的小交互、细节和微动效。',
    'https://designspells.com/',
    '灵感',
    '微交互,动效',
    'Ds',
    'violet',
  ],
  [
    'bento-grids',
    'Bento Grids',
    '查看大小不同的网格如何建立信息层级与视觉节奏。',
    'https://bentogrids.com/',
    '灵感',
    'Bento,布局',
    'B',
    'orange',
  ],
  [
    'spectrum-ui',
    'Spectrum UI',
    '浏览 React 界面组件，参考组件组合与视觉表现。',
    'https://ui.spectrumhq.in/',
    '组件',
    'React,交互',
    'Sp',
    'rose',
  ],
  [
    'dribbble',
    'Dribbble',
    '浏览设计师的 UI 作品，收集排版、配色和局部构图。',
    'https://dribbble.com/',
    '灵感',
    'UI,作品',
    'Dr',
    'rose',
  ],
  [
    'behance',
    'Behance',
    '查看完整设计项目，理解视觉系统在多种页面中的应用。',
    'https://behance.net/',
    '灵感',
    '作品,设计系统',
    'Bē',
    'blue',
  ],
  [
    'awwwards',
    'Awwwards',
    '浏览网站作品与创意交互，记录有用的呈现方式。',
    'https://awwwards.com/',
    '灵感',
    '网站,交互',
    'W.',
    'slate',
  ],
  [
    'siteinspire',
    'SiteInspire',
    '按风格和类型寻找网站，观察克制的布局与排版。',
    'https://siteinspire.com/',
    '灵感',
    '网站,排版',
    'Si',
    'teal',
  ],
  [
    'muzli',
    'Muzli',
    '从设计内容聚合中发现新的作品、工具和阅读线索。',
    'https://muz.li/',
    '灵感',
    '设计资讯,作品',
    'Mu',
    'violet',
  ],
  [
    'land-book',
    'Land-book',
    '按页面类型浏览整站与区块，参考页面的信息组织。',
    'https://land-book.com/',
    '灵感',
    '网站,布局',
    'Lb',
    'teal',
  ],
];

const researched = [
  [
    'ui-ux-pro-max',
    'UI UX Pro Max',
    '把风格、字体、配色和 UX 规则整理成可检索的设计知识。',
    'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill',
    'skills',
    'Skill',
    '设计系统,UI / UX',
    'Ux',
    'blue',
    '适合在设计开始前建立统一规则，再检查页面是否符合这些规则。阅读原仓库的 SKILL.md，并结合当前页面任务选择建议；不要把所有风格同时叠加。',
  ],
  [
    'frontend-design',
    'Frontend Design',
    '从内容和产品用途出发，建立有辨识度的界面方向。',
    'https://github.com/anthropics/skills/tree/main/skills/frontend-design',
    'skills',
    'Skill',
    '视觉设计,前端',
    'Fd',
    'orange',
    'Anthropic 的设计技能。可用于确定排版、配色和布局方向；实施时仍需结合真实内容、组件约束和可访问性。',
  ],
  [
    'impeccable',
    'Impeccable',
    '用设计审查、排版和打磨流程改善已实现的界面。',
    'https://github.com/pbakaus/impeccable',
    'skills',
    'Skill',
    '设计审查,排版',
    'Im',
    'slate',
    '当前主源为 skill/SKILL.src.md。重点可读 critique、layout、typeset、polish、harden 等流程。目录型产品优先采用操作和阅读相关规则。',
  ],
  [
    'taste-skill',
    'Taste Skill',
    '参考极简界面的布局、视觉密度与细节取舍。',
    'https://github.com/Leonxlnx/taste-skill',
    'skills',
    'Skill',
    '极简,布局',
    'Ta',
    'teal',
    '仓库包含多个子技能。资料库可阅读 minimalist-skill；默认技能主要面向落地页和作品集，其中的整屏留白或入场动效不必套用到高频查询界面。',
  ],
  [
    'emil-design',
    'Emil Design Engineering',
    '关注自然的交互反馈、动画曲线与界面的工程细节。',
    'https://github.com/emilkowalski/skills',
    'skills',
    'Skill',
    '动效,交互',
    'E',
    'orange',
    '重点阅读 emil-design-eng 与 prototype。高频搜索和筛选应及时反馈；动画只用于解释状态变化，并尊重减少动态效果的系统偏好。',
  ],
  [
    'web-design-guidelines',
    'Web Design Guidelines',
    '按键盘操作、焦点、表单与动效规则审查网页。',
    'https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines',
    'skills',
    'Skill',
    '可访问性,设计审查',
    'V',
    'slate',
    'Vercel 的界面审查技能。实际规则位于 [Web Interface Guidelines](https://github.com/vercel-labs/web-interface-guidelines/blob/main/command.md)。适合在实现后检查语义、导航、反馈和可访问性。',
  ],
  [
    'stitch-skills',
    'Stitch Skills',
    '学习从设计探索、DESIGN.md 到 React 实现的工作流。',
    'https://github.com/google-labs-code/stitch-skills',
    'skills',
    'Skill',
    '设计系统,工作流',
    'St',
    'violet',
    'Google Labs 的 Stitch 配套技能。可读 design-md 和 generate-design；实际执行相关工具流程需要 Stitch MCP，单独收藏文档并不代表已经接入。',
  ],
  [
    'shadcn-ui',
    'shadcn/ui',
    '将基础组件代码放进项目，按自己的产品需要维护。',
    'https://ui.shadcn.com/docs',
    'web',
    '组件',
    'React,设计系统',
    'sh',
    'slate',
    '参考侧栏、对话框、组合框和表单的结构。组件代码可维护，但安装后仍需检查当前版本、许可和可访问性。',
  ],
  [
    'coss-ui',
    'coss ui',
    '基于 React、Base UI 和 Tailwind 的界面组件。',
    'https://coss.com/ui',
    'web',
    '组件',
    'React,表单',
    'co',
    'blue',
    '适合参考组合框、筛选和内容密集界面。原 originui.com 已转向此入口；当前文档标注 Early Access，采用前应核对接口稳定性。',
  ],
  [
    'magic-ui',
    'Magic UI',
    '收集 React 动效组件，用于适量的交互与展示。',
    'https://magicui.design/docs/components',
    'web',
    '组件',
    'React,动效',
    'Mg',
    'violet',
    '组件仓库采用 MIT；产品中其他付费内容另计。用于功能界面时，应控制动画密度，避免干扰阅读。',
  ],
  [
    'aceternity-ui',
    'Aceternity UI',
    '浏览 React / Next 的卡片、背景、侧栏和页面区块。',
    'https://ui.aceternity.com/',
    'web',
    '组件',
    'React,页面区块',
    'Ac',
    'orange',
    '组件和完整模板的获取范围不同。参考具体布局或交互时，先确认对应代码的许可与依赖。',
  ],
  [
    'cult-ui',
    'Cult UI',
    '观察展开卡片、工具栏、侧面板和 AI 界面交互。',
    'https://www.cult-ui.com/docs',
    'web',
    '组件',
    'React,AI',
    'Cu',
    'teal',
    '可参考紧凑操作区域与状态变化。组件和部分模板的访问条件不同，使用时核对各自的说明。',
  ],
  [
    'kokonut-ui',
    'Kokonut UI',
    '寻找 React / Next 的输入、按钮和轻量动效参考。',
    'https://kokonutui.com/',
    'web',
    '组件',
    'React,动效',
    'Ko',
    'rose',
    '免费开源组件和付费内容并存。资料库中可学习输入区域、按钮层级和交互反馈。',
  ],
  [
    'cruip',
    'Cruip',
    '浏览完整网站模板，学习页面之间如何保持一致。',
    'https://cruip.com/',
    'web',
    '模板',
    'Next.js,布局',
    'Cr',
    'blue',
    '模板以付费为主，也有免费内容。此处作为设计参考收录，没有购买或复制商业模板源码。',
  ],
  [
    'cruip-devspace',
    'DevSpace',
    '参考分类博客、文章摘要和阅读页面的结构。',
    'https://cruip.com/devspace/',
    'web',
    '模板',
    '博客,Next.js',
    'De',
    'teal',
    'Cruip 的博客模板，适合研究笔记目录与正文层级。技术版本和授权范围以产品页为准。',
  ],
  [
    'cruip-docs',
    'Docs Template',
    '参考侧栏目录、文档正文和相邻页面导航。',
    'https://cruip.com/docs-template/',
    'web',
    '模板',
    '文档,Next.js',
    'Do',
    'blue',
    'Cruip 的文档模板。适合学习教程与 Skills 说明的信息组织，不代表本网站使用其源码。',
  ],
  [
    'cruip-jobboard',
    'JobBoard',
    '学习筛选控件、目录列表和详情页如何衔接。',
    'https://cruip.com/jobboard/',
    'web',
    '模板',
    '筛选,Next.js',
    'Jb',
    'orange',
    '借鉴目录型产品的导航方式，按资料库自己的内容改写分类和操作。',
  ],
  [
    'lapa-ninja',
    'Lapa Ninja',
    '按类型和风格浏览整站设计，建立自己的参考板。',
    'https://www.lapa.ninja/',
    'web',
    '灵感',
    '网站,布局',
    'La',
    'violet',
    '同时观察作品和资料站自身的分类方式。可公开浏览部分内容，模板不都使用 React。',
  ],
  [
    'recent-design',
    'Recent',
    '收集网站、产品界面、排版、配色和动效参考。',
    'https://recent.design/',
    'web',
    '灵感',
    '网站,排版',
    'Rc',
    'slate',
    '官方说明该项目接替 Godly。灵感展示不等同于提供作品的源码或复用授权。',
  ],
  [
    'mobbin',
    'Mobbin',
    '从真实产品的屏幕和流程中研究交互体验。',
    'https://mobbin.com/',
    'web',
    'UX',
    '交互,用户流程',
    'Mo',
    'blue',
    '适合研究搜索、分类、空状态和移动端导航。免费访问范围有限，部分流程与搜索需要付费。',
  ],
  [
    'growth-design',
    'Growth.Design',
    '通过产品案例理解选择负担、反馈和引导方式。',
    'https://growth.design/case-studies',
    'web',
    'UX',
    '用户流程,设计心理学',
    'Gd',
    'rose',
    '部分案例可公开阅读，其他内容有访问限制。将案例结论结合自己的用户任务使用，避免把商业转化目标直接套入学习工具。',
  ],
  [
    'laws-of-ux',
    'Laws of UX',
    '理解内容分组、认知负担和已有操作习惯。',
    'https://lawsofux.com/',
    'web',
    'UX',
    '设计原则,信息架构',
    'Lx',
    'orange',
    '从当前界面遇到的问题出发查找原则，例如减少无关选择、建立稳定布局和明确操作反馈。',
  ],
  [
    'one-page-love',
    'One Page Love',
    '浏览单页模板、长页面与可访问的演示。',
    'https://onepagelove.com/templates',
    'web',
    '模板',
    '网站,布局',
    '1P',
    'rose',
    '免费和付费模板混合，技术平台多样。用于观察布局，采用源码前单独确认技术栈和许可。',
  ],
  [
    'awesome-design-md',
    'Awesome DESIGN.md',
    '用结构化文档阅读社区对网站设计系统的分析。',
    'https://github.com/VoltAgent/awesome-design-md',
    'web',
    '指南',
    '设计系统,Markdown',
    'Dm',
    'teal',
    '这些是社区分析，不能当作品牌官方规范。例如 Notion 条目分析官网营销页，并不是 Notion 工作区的完整界面指南。',
  ],
  [
    'lapa-skills',
    'Lapa Design Skills',
    '按设计任务查找技能与其原始来源。',
    'https://www.lapa.ninja/skills/',
    'web',
    '指南',
    'Skill 目录,设计工具',
    'Ls',
    'violet',
    '技能目录用于发现线索。使用前回到原仓库阅读源文件，核对适用场景和工具要求。',
  ],
  [
    'ui-skills',
    'UI Skills',
    '按可访问性、布局和交互主题查找界面技能。',
    'https://www.ui-skills.com/',
    'web',
    '指南',
    'Skill 目录,可访问性',
    'Us',
    'blue',
    '提供技能目录与工具入口；收录目录不表示已经安装其中所有技能。',
  ],
  [
    'ui-skills-playbook',
    'UI Skills Playbook',
    '阅读布局稳定、触控区域、空状态等具体界面经验。',
    'https://www.ui-skills.com/playbook',
    'web',
    'UX',
    '可访问性,设计原则',
    'Pb',
    'slate',
    '适合把短规则转为页面检查项：标题是否易读、控件是否有名称、布局是否稳定、失败后能否继续。',
  ],
  [
    'skills-sh',
    'skills.sh',
    '发现技能，并回到源仓库核对内容和安装范围。',
    'https://skills.sh/',
    'web',
    '指南',
    'Skill 目录,开发工具',
    'sk',
    'slate',
    '选择技能时以源文件和当前任务为依据，不以热度或安装量代替质量判断。',
  ],
];

function writeEntry(folder, slug, data, body) {
  const directory = path.join('content', folder);
  fs.mkdirSync(directory, { recursive: true });
  const file = path.join(directory, `${slug}.md`);
  if (fs.existsSync(file)) return;
  const frontmatter = Object.entries(data)
    .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
    .join('\n');
  fs.writeFileSync(file, `---\n${frontmatter}\n---\n\n${body.trim()}\n`, 'utf8');
}

for (const [slug, title, description, url, kind, tags, mark, color] of original) {
  writeEntry(
    'resources',
    slug,
    {
      title,
      description,
      section: 'web',
      kind,
      url,
      tags: tags.split(','),
      addedAt: '2026-09-14',
      updatedAt: '2026-09-14',
      origin: 'original',
      featured: ['refero', '21st-dev', 'react-bits'].includes(slug),
      mark,
      color,
    },
    `## 关于这份资料\n\n${description}\n\n来自最初的网页设计收藏，保留原始来源入口。\n\n## 阅读时可以关注\n\n- ${tags.split(',')[0]}在真实页面里解决了什么问题？\n- 哪个局部适合自己的项目，采用它需要什么条件？\n- 有没有更简单、对阅读或操作更友好的实现？\n\n## 来源\n\n[访问 ${title}](${url})\n\n作品展示不一定包含源码；复用具体资产或代码前，请查阅来源站点的许可说明。`,
  );
}
for (const [slug, title, description, url, section, kind, tags, mark, color, note] of researched) {
  writeEntry(
    section === 'skills' ? 'skills' : 'resources',
    slug,
    {
      title,
      description,
      section,
      kind,
      url,
      tags: tags.split(','),
      addedAt: '2026-09-14',
      updatedAt: '2026-09-14',
      origin: 'research',
      featured: slug === 'ui-ux-pro-max',
      mark,
      color,
    },
    `## 参考内容\n\n${description}\n\n${note}\n\n## 来源\n\n[查看 ${title} 原始来源](${url})\n\n此条目由设计资源调研整理，尚未记录个人实践结果。`,
  );
}
console.log(
  `Initial catalogue prepared: ${original.length} original resources + ${researched.length} researched resources.`,
);
